name: Build MCP Servers

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker - markdown-to-html
        id: meta-markdown-to-html
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/markdown-to-html

      - name: Build and push Docker image - markdown-to-html - stdio
        id: push-markdown-to-html-stdio
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ github.workspace }}/markdown-to-html
          file: ${{ github.workspace }}/markdown-to-html/Dockerfile.stdio
          tags: '${{ steps.meta-markdown-to-html.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/markdown-to-html:stdio'
          labels: ${{ steps.meta-markdown-to-html.outputs.labels }}

      - name: Generate artifact attestation - markdown-to-html - stdio
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/markdown-to-html
          subject-digest: ${{ steps.push-markdown-to-html-stdio.outputs.digest }}
          push-to-registry: true

      - name: Build and push Docker image - markdown-to-html - http
        id: push-markdown-to-html-http
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ github.workspace }}/markdown-to-html
          file: ${{ github.workspace }}/markdown-to-html/Dockerfile.http
          tags: '${{ steps.meta-markdown-to-html.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/markdown-to-html:http'
          labels: ${{ steps.meta-markdown-to-html.outputs.labels }}

      - name: Generate artifact attestation - markdown-to-html - http
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/markdown-to-html
          subject-digest: ${{ steps.push-markdown-to-html-http.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata (tags, labels) for Docker - todo-list - http
        id: meta-todo-list
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todo-list

      - name: Build and push Docker image - todo-list - http
        id: push-todo-list-http
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ github.workspace }}/todo-list
          file: ${{ github.workspace }}/todo-list/Dockerfile
          tags: '${{ steps.meta-todo-list.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todo-list:http'
          labels: ${{ steps.meta-todo-list.outputs.labels }}

      - name: Generate artifact attestation - todo-list
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/todo-list
          subject-digest: ${{ steps.push-todo-list-http.outputs.digest }}
          push-to-registry: true
